[book]
authors = ["parasaurolophus"]
language = "en"
multilingual = false
src = "src"
title = "Kirk Rader"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
mathjax-support = true